#!/usr/bin/env python3
"""Generate the parity matrix: every macro against every trait shape.

The four macros are supposed to accept the same traits. They did not: seventeen of the
forty cells failed to compile, and which seventeen differed per macro, so a trait that
worked under `#[as_any]` could fail under `#[clone_box]` with an error pointing at the
caller's own source. Writing the matrix by hand is how that stays true, because a hand
written matrix is one somebody can leave a row out of.

Run from the repo root: python3 tests/parity/generate.py
"""
import pathlib

# A shape, and whether a macro that must form `dyn Trait` can accept it. Every shape here
# is ordinary Rust that a caller may reasonably write.
SHAPES = [
    ("plain_empty",    "pub trait {t} {{}}",                                              True),
    ("plain_methods",  "pub trait {t} {{ fn f(&self) -> u8; }}",                          True),
    ("generic",        "pub trait {t}<A> {{ fn f(&self) -> A; }}",                        True),
    ("generic_bound",  "pub trait {t}<A: Clone> {{ fn f(&self) -> A; }}",                 True),
    ("lifetime",       "pub trait {t}<'a> {{ fn f(&self) -> &'a u8; }}",                  True),
    ("supertrait",     "pub trait {t}: ::core::fmt::Debug {{ fn f(&self); }}",            True),
    ("where_clause",   "pub trait {t}<A> where A: Clone {{ fn f(&self) -> A; }}",         True),
    ("const_generic",  "pub trait {t}<const N: usize> {{ fn f(&self) -> [u8; N]; }}",     True),
    ("default_method", "pub trait {t} {{ fn f(&self) -> u8 {{ 1 }} }}",                   True),
    # `dyn T` is not a type while an associated type is unnamed, so the three macros that
    # must form one refuse it with a diagnostic of their own. `as_any` forms only `dyn Any`
    # and is unaffected, which is a difference in what the language permits rather than a
    # difference in the macros.
    ("assoc_type",     "pub trait {t} {{ type A; fn f(&self) -> Self::A; }}",             False),
]

MACROS = ["as_any", "as_super", "clone_box", "obj_eq"]
FORMS_DYN = {"as_super", "clone_box", "obj_eq"}

header = """//------------------------------------------------------------------------------
// Copyright (c) 2025 orgrinrt (orgrinrt@ikiuni.dev)
//                    Hiisi Digital Oy (contact@hiisi.digital)
// SPDX-License-Identifier: MPL-2.0
//------------------------------------------------------------------------------

//! GENERATED by tests/parity/generate.py. Do not edit; edit the generator.
//!
//! Every macro against every trait shape. A cell that compiles is a shape that macro
//! accepts, and the point of the file is that the column is the same for all four wherever
//! the language allows it to be.

#![allow(dead_code)]

"""

cells = []
count = 0
for mac in MACROS:
    cells.append(f"mod {mac}_shapes {{\n    use objkit::{mac};\n")
    for sname, tmpl, dyn_ok in SHAPES:
        if sname == "assoc_type" and mac in FORMS_DYN:
            continue  # refused, and asserted as a compile-fail case instead
        body = tmpl.format(t="".join(part.capitalize() for part in sname.split("_")))
        cells.append(f"    #[{mac}]\n    {body}\n")
        count += 1
    cells.append("}\n\n")

# The generator refuses to write an empty file, which is where the guard belongs. A guard
# inside the generated file can only compare numbers this script emitted, and two numbers
# from one variable agree whatever the variable is; an earlier version asserted exactly
# that and passed on an empty matrix.
if count == 0:
    raise SystemExit(
        "generate.py: no cells. The matrix is the assertion, so an empty file would be a "
        "suite that passes by testing nothing. Check SHAPES and MACROS."
    )

body = header + "".join(cells)
body += f"""// The matrix is the assertion: this file compiling is {count} cells passing, one per
// macro per trait shape. There is no `#[test]` here on purpose. A test in this file could
// only compare numbers the generator wrote, and any two of those agree by construction;
// the guard that matters is the generator refusing to produce an empty file, which is in
// generate.py rather than here.
"""

out = pathlib.Path("tests/parity_matrix.rs")
out.write_text(body)
print(f"{count} cells over {len(MACROS)} macros and {len(SHAPES)} shapes -> {out}")
