[workspace]
dependencies-order = true
publish = true

[packages."objkit-shared"]
[packages."objkit-macros"]
[packages."objkit"]

[release.github]
token = "env:GITHUB_TOKEN"
owner = "orgrinrt"
repository = "objkit"
tag-name = "{{version}}"
name = "Release {{version}}"
draft = false
body = "env:GITHUB_RELEASE_BODY"
