//------------------------------------------------------------------------------
// Copyright (c) 2025 orgrinrt (orgrinrt@ikiuni.dev)
//                    Hiisi Digital Oy (contact@hiisi.digital)
// SPDX-License-Identifier: MPL-2.0
//------------------------------------------------------------------------------

//! GENERATED by tests/parity/generate.py. Do not edit; edit the generator.
//!
//! Every macro against every trait shape. A cell that compiles is a shape that macro
//! accepts, and the point of the file is that the column is the same for all four wherever
//! the language allows it to be.

#![allow(dead_code)]

mod as_any_shapes {
    use objkit::as_any;
    #[as_any]
    pub trait PlainEmpty {}
    #[as_any]
    pub trait PlainMethods { fn f(&self) -> u8; }
    #[as_any]
    pub trait Generic<A> { fn f(&self) -> A; }
    #[as_any]
    pub trait GenericBound<A: Clone> { fn f(&self) -> A; }
    #[as_any]
    pub trait Lifetime<'a> { fn f(&self) -> &'a u8; }
    #[as_any]
    pub trait Supertrait: ::core::fmt::Debug { fn f(&self); }
    #[as_any]
    pub trait WhereClause<A> where A: Clone { fn f(&self) -> A; }
    #[as_any]
    pub trait ConstGeneric<const N: usize> { fn f(&self) -> [u8; N]; }
    #[as_any]
    pub trait DefaultMethod { fn f(&self) -> u8 { 1 } }
    #[as_any]
    pub trait AssocType { type A; fn f(&self) -> Self::A; }
}

mod as_super_shapes {
    use objkit::as_super;
    #[as_super]
    pub trait PlainEmpty {}
    #[as_super]
    pub trait PlainMethods { fn f(&self) -> u8; }
    #[as_super]
    pub trait Generic<A> { fn f(&self) -> A; }
    #[as_super]
    pub trait GenericBound<A: Clone> { fn f(&self) -> A; }
    #[as_super]
    pub trait Lifetime<'a> { fn f(&self) -> &'a u8; }
    #[as_super]
    pub trait Supertrait: ::core::fmt::Debug { fn f(&self); }
    #[as_super]
    pub trait WhereClause<A> where A: Clone { fn f(&self) -> A; }
    #[as_super]
    pub trait ConstGeneric<const N: usize> { fn f(&self) -> [u8; N]; }
    #[as_super]
    pub trait DefaultMethod { fn f(&self) -> u8 { 1 } }
}

mod clone_box_shapes {
    use objkit::clone_box;
    #[clone_box]
    pub trait PlainEmpty {}
    #[clone_box]
    pub trait PlainMethods { fn f(&self) -> u8; }
    #[clone_box]
    pub trait Generic<A> { fn f(&self) -> A; }
    #[clone_box]
    pub trait GenericBound<A: Clone> { fn f(&self) -> A; }
    #[clone_box]
    pub trait Lifetime<'a> { fn f(&self) -> &'a u8; }
    #[clone_box]
    pub trait Supertrait: ::core::fmt::Debug { fn f(&self); }
    #[clone_box]
    pub trait WhereClause<A> where A: Clone { fn f(&self) -> A; }
    #[clone_box]
    pub trait ConstGeneric<const N: usize> { fn f(&self) -> [u8; N]; }
    #[clone_box]
    pub trait DefaultMethod { fn f(&self) -> u8 { 1 } }
}

mod obj_eq_shapes {
    use objkit::obj_eq;
    #[obj_eq]
    pub trait PlainEmpty {}
    #[obj_eq]
    pub trait PlainMethods { fn f(&self) -> u8; }
    #[obj_eq]
    pub trait Generic<A> { fn f(&self) -> A; }
    #[obj_eq]
    pub trait GenericBound<A: Clone> { fn f(&self) -> A; }
    #[obj_eq]
    pub trait Lifetime<'a> { fn f(&self) -> &'a u8; }
    #[obj_eq]
    pub trait Supertrait: ::core::fmt::Debug { fn f(&self); }
    #[obj_eq]
    pub trait WhereClause<A> where A: Clone { fn f(&self) -> A; }
    #[obj_eq]
    pub trait ConstGeneric<const N: usize> { fn f(&self) -> [u8; N]; }
    #[obj_eq]
    pub trait DefaultMethod { fn f(&self) -> u8 { 1 } }
}

/// The matrix is the assertion: this file compiling is 37 cells passing.
///
/// Counted here so that a generator producing an empty file fails rather than passing
/// silently, which is the way a generated suite usually dies.
#[test]
fn every_cell_in_the_matrix_compiled() {
    assert_eq!(CELLS, 37, "the generator wrote a different number of cells");
}

const CELLS: usize = 37;
