[package]
name = "objkit-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true
include_proc_macro.workspace = true
typeable = { version = "0.1", optional = true }
siphasher = { version = "1.0.1", optional = true }

[features]
std_box = []
alloc_box = []
# the two main variants
std = ["std_box"]
no_std = ["typeable", "siphasher", "alloc_box"]
